export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_REQUEST= 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_CLEAR = 'FILE_UPLOAD_CLEAR';