export const GET_PRODUCT_CATEGORY_ERROR = 'GET_PRODUCT_CATEGORY_ERROR';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_REQUEST= 'GET_PRODUCT_CATEGORY_REQUEST';
export const GET_PRODUCT_CATEGORY_CLEAR = 'GET_PRODUCT_CATEGORY_CLEAR';

export const CREATE_PRODUCT_CATEGORY_ERROR = 'CREATE_PRODUCT_CATEGORY_ERROR';
export const CREATE_PRODUCT_CATEGORY_SUCCESS = 'CREATE_PRODUCT_CATEGORY_SUCCESS';
export const CREATE_PRODUCT_CATEGORY_REQUEST= 'CREATE_PRODUCT_CATEGORY_REQUEST';
export const CREATE_PRODUCT_CATEGORY_CLEAR = 'CREATE_PRODUCT_CATEGORY_CLEAR';

export const UPDATE_PRODUCT_CATEGORY_ERROR = 'UPDATE_PRODUCT_CATEGORY_ERROR';
export const UPDATE_PRODUCT_CATEGORY_SUCCESS = 'UPDATE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_PRODUCT_CATEGORY_REQUEST= 'UPDATE_PRODUCT_CATEGORY_REQUEST';
export const UPDATE_PRODUCT_CATEGORY_CLEAR = 'UPDATE_PRODUCT_CATEGORY_CLEAR';

export const DETAIL_PRODUCT_CATEGORY_SUCCESS = 'DETAIL_PRODUCT_CATEGORY_SUCCESS';
export const DETAIL_PRODUCT_CATEGORY_REQUEST= 'DETAIL_PRODUCT_CATEGORY_REQUEST';
export const DETAIL_PRODUCT_CATEGORY_CLEAR = 'DETAIL_PRODUCT_CATEGORY_CLEAR';
export const DETAIL_PRODUCT_CATEGORY_ERROR = 'DETAIL_PRODUCT_CATEGORY_ERROR';

export const DELETE_PRODUCT_CATEGORY_SUCCESS = 'DELETE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_PRODUCT_CATEGORY_REQUEST= 'DELETE_PRODUCT_CATEGORY_REQUEST';
export const DELETE_PRODUCT_CATEGORY_CLEAR = 'DELETE_PRODUCT_CATEGORY_CLEAR';
export const DELETE_PRODUCT_CATEGORY_ERROR = 'DELETE_PRODUCT_CATEGORY_ERROR';