export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_REQUEST= 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_CLEAR = 'GET_PRODUCT_CLEAR';

export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_REQUEST= 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_CLEAR = 'CREATE_PRODUCT_CLEAR';

export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_REQUEST= 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_CLEAR = 'UPDATE_PRODUCT_CLEAR';

export const DETAIL_PRODUCT_SUCCESS = 'DETAIL_PRODUCT_SUCCESS';
export const DETAIL_PRODUCT_REQUEST= 'DETAIL_PRODUCT_REQUEST';
export const DETAIL_PRODUCT_CLEAR = 'DETAIL_PRODUCT_CLEAR';
export const DETAIL_PRODUCT_ERROR = 'DETAIL_PRODUCT_ERROR';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_REQUEST= 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_CLEAR = 'DELETE_PRODUCT_CLEAR';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const DELETE_PRODUCT_IMAGE_SUCCESS = 'DELETE_PRODUCT_IMAGE_SUCCESS';
export const DELETE_PRODUCT_IMAGE_REQUEST= 'DELETE_PRODUCT_IMAGE_REQUEST';
export const DELETE_PRODUCT_IMAGE_CLEAR = 'DELETE_PRODUCT_IMAGE_CLEAR';
export const DELETE_PRODUCT_IMAGE_ERROR = 'DELETE_PRODUCT_IMAGE_ERROR';