export const USER_CURRENT_ERROR = 'USER_CURRENT_ERROR';
export const USER_CURRENT_SUCCESS = 'USER_CURRENT_SUCCESS';
export const USER_CURRENT_REQUEST = 'USER_CURRENT_REQUEST';
export const USER_CURRENT_CLEAR = 'USER_CURRENT_CLEAR';